export default [
  {
    id: 1,
    title: 'Old City',
    location: 'Azerbaijan',
    googleMapsUrlId: 'z4ZuPDhjgEY3a53p7',
    startDate: '10 Oct, 2022',
    endDate: '12 Nov, 2022',
    description:
      'Walled Old City featuring 1100s fortifications & towers, plus iconic, ornate palaces & mosques.',
    imageUrlId: '1622314621630-0d24bcb5aa67',
    wikipediaId: 'Old_City_(Baku)',
  },
  {
    id: 2,
    title: 'Mount Fuji',
    location: 'Japan',
    googleMapsUrlId: '1DGM5WrWnATgkSNB8',
    startDate: '12 Jan, 2021',
    endDate: '24 Jan, 2021',
    description:
      'Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.',
    imageUrlId: '1589308078059-be1415eab4c3',
    wikipediaId: 'Mount_Fuji',
  },
  {
    id: 3,
    title: 'Sydney Opera House',
    location: 'Australia',
    googleMapsUrlId: 'SM2xLyumv6kp7WAi8',
    startDate: '27 May, 2021',
    endDate: '8 Jun, 2021',
    description:
      'The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th centurys most famous and distinctive buildings',
    imageUrlId: '1624138784614-87fd1b6528f8',
    wikipediaId: 'Sydney_Opera_House',
  },
  {
    id: 4,
    title: 'Geirangerfjord',
    location: 'Norway',
    googleMapsUrlId: 'JsFsLamhFRAGeqv27',
    startDate: '01 Oct, 2021',
    endDate: '18 Nov, 2021',
    description:
      'The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.',
    imageUrlId: '1601439678777-b2b3c56fa627',
    wikipediaId: 'Geirangerfjord',
  },
  {
    id: 5,
    title: 'Great Wall of China',
    location: 'China',
    googleMapsUrlId: 'Fu2fD7qv8iXwBWtq7',
    startDate: '10 Dec, 2022',
    endDate: '23 Dec, 2022',
    description:
      'Ancient world wonder that winds for more than 5,500 miles across China, with towers & walkways.',
    imageUrlId: '1572851819189-7d4b51a3c029',
    wikipediaId: 'Great_Wall_of_China',
  },
  {
    id: 6,
    title: 'Giza Necropolis',
    location: 'Egypt',
    googleMapsUrlId: 'RMErHjdF7FdfZUAQ7',
    startDate: '20 Jan, 2023',
    endDate: '27 Jan, 2023',
    description:
      'Famed archaeological site featuring the Great Pyramids, the Great Sphinx & other well-known ruins.',
    imageUrlId: '1643667802197-ce810e01619d',
    wikipediaId: 'Giza_pyramid_complex',
  },
  {
    id: 7,
    title: 'Taj Mahal',
    location: 'India',
    googleMapsUrlId: 'qEp8xyDwExKVPmj27',
    startDate: '12 Feb, 2023',
    endDate: '24 Feb, 2023',
    description:
      '17th-century, Mughal-style, marble mausoleum with minarets, a mosque & famously symmetrical gardens.',
    imageUrlId: '1598324789736-4861f89564a0',
    wikipediaId: 'Taj_Mahal',
  },
  {
    id: 8,
    title: 'Colosseum',
    location: 'Italy',
    googleMapsUrlId: 'rNWHTw3UwTfbAkHXA',
    startDate: '20 Feb, 2023',
    endDate: '30 Feb, 2023',
    description:
      'Monumental 3-tiered Roman amphitheater once used for gladiatorial games, with guided tour option.',
    imageUrlId: '1634196243663-71cc3a1c639a',
    wikipediaId: 'Colosseum',
  },
  {
    id: 9,
    title: 'Eiffel Tower',
    location: 'France',
    googleMapsUrlId: 'k4viE8xJomUtXg4h8',
    startDate: '03 Apr, 2023',
    endDate: '23 Apr, 2023',
    description:
      'Gustave Eiffels iconic, wrought-iron 1889 tower, with steps and elevators to observation decks.',
    imageUrlId: '1604175287072-b5e71423060c',
    wikipediaId: 'Eiffel_Tower',
  },
  {
    id: 10,
    title: 'Victoria Falls',
    location: 'Zimbabwe',
    googleMapsUrlId: 'wumdLH6LrQfvSjyB6',
    startDate: '12 Apr, 2023',
    endDate: '26 Apr, 2023',
    description:
      'Victoria Falls is a waterfall on the Zambezi River in southern Africa, which provides habitat for several unique species of plants and animals.',
    imageUrlId: '1603201236596-eb1a63eb0ede',
    wikipediaId: 'Victoria_Falls',
  },
];
